title : Hack Weekends Guide

safe: true
lsi: false
pygments: true
auto: true

source: hack-weekends-guide
destination: hack-weekends-guide

production_url : https://loopglitch26.github.io/hack-weekends-guide/

BASE_PATH : https://loopglitch26.github.io/hack-weekends-guide/
